Document: librtmr
Title: Debian librtmr Manual
Author: <insert document author here>
Abstract: This manual describes what librtmr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/librtmr/librtmr.sgml.gz

Format: postscript
Files: /usr/share/doc/librtmr/librtmr.ps.gz

Format: text
Files: /usr/share/doc/librtmr/librtmr.text.gz

Format: HTML
Index: /usr/share/doc/librtmr/html/index.html
Files: /usr/share/doc/librtmr/html/*.html
