Document: netserver
Title: Debian netserver Manual
Author: <insert document author here>
Abstract: This manual describes what netserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/netserver/netserver.sgml.gz

Format: postscript
Files: /usr/share/doc/netserver/netserver.ps.gz

Format: text
Files: /usr/share/doc/netserver/netserver.text.gz

Format: HTML
Index: /usr/share/doc/netserver/html/index.html
Files: /usr/share/doc/netserver/html/*.html
